name: tests-BST
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  tests:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linter
        run: |
          pip3 install flake8 pep8-naming
          flake8 containers/BST.py --ignore=E501
      - name: Run tests
        run: |
          python -m pytest tests/test_BST.py


